update

diff --git a/devices/common/patches/selective_restore.patch b/devices/common/patches/selective_restore.patch
--- a/devices/common/patches/selective_restore.patch
+++ b/devices/common/patches/selective_restore.patch
@@ -237,3 +237,143 @@ index b096d870a754..2991613ef1af 100644
  				"/tmp/backup.tar.gz": [ "write" ],
  				"/tmp/firmware.bin": [ "write" ]
  			},
+--- a/package/base-files/files/sbin/sysupgrade
++++ b/package/base-files/files/sbin/sysupgrade
+@@ -22,6 +22,8 @@ CONF_BACKUP_LIST=0
+ CONF_BACKUP=
+ CONF_RESTORE=
+ USE_CURR_PART=0
++CONF_SELECTIVE_RESTORE=
++CONF_SELECTIVE_RESTORE_FILELIST=
+ NEED_IMAGE=
+ HELP=0
+ TEST=0
+@@ -51,6 +53,7 @@ while [ -n "$1" ]; do
+ 		-u) SKIP_UNCHANGED=1;;
+ 		-b|--create-backup) CONF_BACKUP="$2" NEED_IMAGE=1; shift;;
+ 		-r|--restore-backup) CONF_RESTORE="$2" NEED_IMAGE=1; shift;;
++		-S|--selectively-restore-backup) CONF_SELECTIVE_RESTORE_FILELIST="$2" CONF_SELECTIVE_RESTORE="$3" NEED_IMAGE=1; shift;shift;;
+ 		-l|--list-backup) CONF_BACKUP_LIST=1;;
+ 		-f) CONF_IMAGE="$2"; shift;;
+ 		-s) USE_CURR_PART=1;;
+@@ -105,6 +108,11 @@ backup-command:
+ 	             restore a .tar.gz created with sysupgrade -b
+ 	             then exit. Does not flash an image. If file is '-',
+ 	             the archive is read from stdin.
++	-S | --selectively-restore-backup <file-with-list-of-filenames> <file>
++	             selectively restore a .tar.gz created with sysupgrade -b
++	             by passing a file containing the desired list of filenames,
++	             then exit. Does not flash an image. If file is '-',
++	             the archive is read from stdin.
+ 	-l | --list-backup
+ 	             list the files that would be backed up when calling
+ 	             sysupgrade -b. Does not create a backup file.
+@@ -351,6 +359,22 @@ if [ -n "$CONF_RESTORE" ]; then
+ 	exit $?
+ fi
+ 
++if [ -n "$CONF_SELECTIVE_RESTORE" ]; then
++	if [ "$CONF_SELECTIVE_RESTORE" != "-" ] && [ ! -f "$CONF_SELECTIVE_RESTORE" ]; then
++		echo "Backup archive '$CONF_SELECTIVE_RESTORE' not found." >&2
++		exit 1
++	fi
++
++	[ "$VERBOSE" -gt 1 ] && TAR_V="v" || TAR_V=""
++	v "Selectively restoring config files..."
++	if [ "$(type -t platform_restore_backup)" = 'platform_restore_backup' ]; then
++		platform_selectively_restore_backup "$TAR_V"
++	else
++		tar -C / -x"${TAR_V}"zf "$CONF_SELECTIVE_RESTORE" -T "$CONF_SELECTIVE_RESTORE_FILELIST"
++	fi
++	exit $?
++fi
++
+ type platform_check_image >/dev/null 2>/dev/null || {
+ 	echo "Firmware upgrade is not implemented for this platform." >&2
+ 	exit 1
+diff --git a/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh b/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
+index 69cc60e2bcb095..b7fffd68b4b450 100644
+--- a/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
++++ b/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
+@@ -128,3 +128,10 @@ platform_restore_backup() {
+ 	tar -C / -x${TAR_V}zf "$CONF_RESTORE"
+ 	bcm27xx_set_root_part
+ }
++
++platform_selectively_restore_backup() {
++	local TAR_V=$1
++
++	tar -C / -x${TAR_V}zf "$CONF_RESTORE" -T "$CONF_SELECTIVE_RESTORE_FILELIST"
++	bcm27xx_set_root_part
++}
+diff --git a/package/base-files/files/sbin/sysupgrade b/package/base-files/files/sbin/sysupgrade
+index 75817d178aea18..4a51304f771e20 100755
+--- a/package/base-files/files/sbin/sysupgrade
++++ b/package/base-files/files/sbin/sysupgrade
+@@ -22,6 +22,8 @@ CONF_BACKUP_LIST=0
+ CONF_BACKUP=
+ CONF_RESTORE=
+ USE_CURR_PART=0
++CONF_SELECTIVE_RESTORE=
++CONF_SELECTIVE_RESTORE_FILELIST=
+ NEED_IMAGE=
+ HELP=0
+ TEST=0
+@@ -51,6 +53,7 @@ while [ -n "$1" ]; do
+ 		-u) SKIP_UNCHANGED=1;;
+ 		-b|--create-backup) CONF_BACKUP="$2" NEED_IMAGE=1; shift;;
+ 		-r|--restore-backup) CONF_RESTORE="$2" NEED_IMAGE=1; shift;;
++		-S|--selectively-restore-backup) CONF_SELECTIVE_RESTORE_FILELIST="$2" CONF_SELECTIVE_RESTORE="$3" NEED_IMAGE=1; shift;shift;;
+ 		-l|--list-backup) CONF_BACKUP_LIST=1;;
+ 		-f) CONF_IMAGE="$2"; shift;;
+ 		-s) USE_CURR_PART=1;;
+@@ -105,6 +108,11 @@ backup-command:
+ 	             restore a .tar.gz created with sysupgrade -b
+ 	             then exit. Does not flash an image. If file is '-',
+ 	             the archive is read from stdin.
++	-S | --selectively-restore-backup <file-with-list-of-filenames> <file>
++	             selectively restore a .tar.gz created with sysupgrade -b
++	             by passing a file containing the desired list of filenames,
++	             then exit. Does not flash an image. If file is '-',
++	             the archive is read from stdin.
+ 	-l | --list-backup
+ 	             list the files that would be backed up when calling
+ 	             sysupgrade -b. Does not create a backup file.
+@@ -351,6 +359,22 @@ if [ -n "$CONF_RESTORE" ]; then
+ 	exit $?
+ fi
+ 
++if [ -n "$CONF_SELECTIVE_RESTORE" ]; then
++	if [ "$CONF_SELECTIVE_RESTORE" != "-" ] && [ ! -f "$CONF_SELECTIVE_RESTORE" ]; then
++		echo "Backup archive '$CONF_SELECTIVE_RESTORE' not found." >&2
++		exit 1
++	fi
++
++	[ "$VERBOSE" -gt 1 ] && TAR_V="v" || TAR_V=""
++	v "Selectively restoring config files..."
++	if [ "$(type -t platform_restore_backup)" = 'platform_restore_backup' ]; then
++		platform_selectively_restore_backup "$TAR_V"
++	else
++		tar -C / -x"${TAR_V}"zf "$CONF_SELECTIVE_RESTORE" -T "$CONF_SELECTIVE_RESTORE_FILELIST"
++	fi
++	exit $?
++fi
++
+ type platform_check_image >/dev/null 2>/dev/null || {
+ 	echo "Firmware upgrade is not implemented for this platform." >&2
+ 	exit 1
+diff --git a/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh b/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
+index 69cc60e2bcb095..b7fffd68b4b450 100644
+--- a/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
++++ b/target/linux/bcm27xx/base-files/lib/upgrade/platform.sh
+@@ -128,3 +128,10 @@ platform_restore_backup() {
+ 	tar -C / -x${TAR_V}zf "$CONF_RESTORE"
+ 	bcm27xx_set_root_part
+ }
++
++platform_selectively_restore_backup() {
++	local TAR_V=$1
++
++	tar -C / -x${TAR_V}zf "$CONF_RESTORE" -T "$CONF_SELECTIVE_RESTORE_FILELIST"
++	bcm27xx_set_root_part
++}
